name: CD

on:
  push:
    branches:
      - main

jobs:
  call-terraform:
    uses: barrcraft/oshi-gha-workflows/.github/workflows/terraform/apply.yml@main
    with:
      image_tag: ${{ github.sha }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
