name: CI

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    uses: barrcraft/oshi-gha-workflows/.github/workflows/docker/build.yml@main
    with:
      image_tag: ${{ github.sha }}

  publish-aws-ecr:
    uses: barrcraft/oshi-gha-workflows/.github/workflows/aws/publish-ecr.yml@main
    with:
      aws_region: us-east-2
      ecr_repository
      image_tag: ${{ github.sha }}
      service_name: devops-interview-demo
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
